### ISSUE TITLE
Just a simple question ......

### ISSUE THREAD

**Issue by oywino** [slyoldfox/c300x-dashboard#1]
..... and please forgive me for asking here. My question belong in the C300x-controller repo, but there is no `Issues `tab there (!) - so I'm taking my chances here. 
My "issue" is as follows:
Is the c300x-controller API compatible with the Bticino CLASSE 100X16E ?  
( https://www.bticino.com/products/door-entry-systems/2-wires-internal-solutions/classe-100-internal-units/features-and-benefits )

**Comment by slyoldfox** [comment]
If there's no issues tab that's because I don't want to deal with questions like this on github, use the telegram channel https://t.me/bTicinoClasse300x - and yes, in therory it does.
